# Allometric equation uncertainty

In [1]:
import allometry
import pandas as pd
import numpy as np
from scipy.optimize import curve_fit

In [2]:
# Load harvest data from Chave et al 2014
har = pd.read_csv("../Chave_harvest_db/Chave_GCB_Direct_Harvest_Data.csv")
loc = pd.read_csv("../Chave_harvest_db/Localities.csv")
loc['Forest_type'] = loc.Forest_type.str.replace(' forest','')
print har.columns
print loc.columns

Index([u'Site', u'DBH_cm', u'Total_height_m', u'AGB_kg', u'Gravity'], dtype='object')
Index([u'Abbreviation', u'Tree_count', u'2005_avail', u'Latitude',
       u'Longitude', u'Locality', u'Forest_type', u'Successional_type',
       u'Mean_annual_temperature', u'Temp_Seasonality', u'Mean_Annual_Precip',
       u'Precip_Seasonality_perc', u'Altitude', u'Evapotranspiration_mm_yr',
       u'Dry_months', u'CWD_mm_yr', u'Ref'],
      dtype='object')


In [3]:
# Select harvest data from South America
sa = loc[loc.Locality.str.contains('Brazil') | loc.Locality.str.contains('Colombia') |
         loc.Locality.str.contains('Venezuela') | loc.Locality.str.contains('Peru') |
         loc.Locality.str.contains('French Guiana') | loc.Locality.str.contains('Costa Rica')
        ]['Abbreviation'].tolist()

sahar = har[har.Site.isin(sa)]
sahar.Site.unique()

array(['BraMan2', 'BraPara1', 'BraPara3', 'BraRond', 'ColombiaC1',
       'ColombiaG1', 'ColombiaG2', 'ColombiaM1', 'ColombiaM2', 'CostaRic',
       'FrenchGu', 'Llanosec', 'Llanosol', 'MFrenchG', 'Peru', 'SaoPaulo3',
       'SouthBrazil1', 'SouthBrazil2', 'SouthBrazil3', 'Venezuela2'], dtype=object)

In [4]:
# allometric functions
def est_alvarez(row):
    return allometry.alvarez(row.DBH_cm, row.Gravity, row.Holdridge)

def est_chaveI(row):
    fo = loc[loc.Abbreviation == row.Site]['Forest_type'].item()
    return allometry.chaveI(row.DBH_cm, row.Gravity, fo)

def est_chaveI_or(row):
    fo = loc[loc.Abbreviation == row.Site]['Forest_type'].item()
    return allometry.chaveI_original(row.DBH_cm, row.Gravity, fo)

def est_E(row):
    #E = ( 0.178 × TS-0.938 × CWD-6.61× PS ) ×10 −3
    ts = loc[loc.Abbreviation == row.Site]['Temp_Seasonality'].item()
    cwd = loc[loc.Abbreviation == row.Site]['CWD_mm_yr'].item()
    ps = loc[loc.Abbreviation == row.Site]['Precip_Seasonality_perc'].item()
    E = (0.178 * ts - 0.938 * cwd - 6.61 * ps) * 1e-3
    return E

def est_holdr(row):
    alt = loc[loc.Abbreviation == row.Site]['Altitude'].item()
    prep = loc[loc.Abbreviation == row.Site]['Mean_Annual_Precip'].item()
    return allometry.holdridge_col(alt, prep)

def est_chaveII(row):
    return allometry.chaveII(row.DBH_cm, row.Gravity, e_value = row.E)

In [5]:
har['E'] = har.apply(est_E, axis=1)
sahar.loc[:,'Holdridge'] = sahar.apply(est_holdr, axis=1)

har['ChaveI'] = har.apply(est_chaveI, axis=1)
har['ChaveI_or'] = har.apply(est_chaveI_or, axis=1)
har['ChaveII'] = har.apply(est_chaveII, axis=1)
sahar.loc[:,'Alvarez'] = sahar.apply(est_alvarez, axis=1)

/home/nelsonsalinas/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py:357: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/nelsonsalinas/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [6]:
# Estimate errors
har['ChaveI_error'] = (np.log(har.ChaveI) - np.log(har.AGB_kg))**2
har['ChaveI_or_error'] = (np.log(har.ChaveI_or) - np.log(har.AGB_kg))**2
har['ChaveII_error'] = (np.log(har.ChaveII) - np.log(har.AGB_kg))**2
sahar.loc[:,'Alvarez_error'] = (np.log(sahar.Alvarez) - np.log(sahar.AGB_kg))**2

In [7]:
# SEEs
print (har.ChaveI_error.sum() / (har.shape[0]-4))**0.5
print (har.ChaveI_or_error.sum() / (har.shape[0]-4))**0.5
print (har.ChaveII_error.sum() / (har.shape[0]-5))**0.5
print (sahar.Alvarez_error.sum() / (sahar.shape[0]-5))**0.5

0.597036288929
0.57808567889
0.420779217764
0.560882175149


## Fit equation via least squares

In [19]:
def chave2005(X, a, b, c, d):
    dap, den = X
    out = a + b * np.log(dap) + c * np.log(dap)**2 + d * np.log(dap)**3 + np.log(den)
    return out

def chave2014(X, a, b, c, d, e):
    E, den, dap = X
    out = a + b * E + c * np.log(den) + d * np.log(dap) + e * np.log(dap)**2
    return out

In [9]:
curve_fit(chave2005, (har.DBH_cm, har.Gravity), np.log(har.AGB_kg))

(array([-3.35030644,  3.68832942, -0.29566994,  0.02574888]),
 array([[ 0.12942566, -0.13359906,  0.04347523, -0.00448497],
        [-0.13359906,  0.13954395, -0.04588297,  0.00477556],
        [ 0.04347523, -0.04588297,  0.01523812, -0.00160049],
        [-0.00448497,  0.00477556, -0.00160049,  0.00016959]]))

In [20]:
har['ChaveI_new'] = np.exp(chave2005((har.DBH_cm, har.Gravity), -3.350, 3.688, -0.296, 0.026))
har['ChaveI_new_error'] = (np.log(har.ChaveI_new) - np.log(har.AGB_kg))**2
cf = har.ChaveI_new_error.sum() / (har.shape[0]-4)
print "SEE:", cf ** 0.5
print "CF:", np.exp(cf / 2)
print "log CF:", cf / 2

SEE: 0.526537644398
CF: 1.14868860187
log CF: 0.138620945484


In [11]:
curve_fit(chave2014, (har.E, har.Gravity, har.DBH_cm), np.log(har.AGB_kg))

(array([-2.10942259, -0.89647401,  0.92284733,  2.79430146, -0.04585078]),
 array([[  6.98923097e-03,  -2.73651475e-04,   2.46197208e-04,
          -4.58184091e-03,   7.17341406e-04],
        [ -2.73651475e-04,   3.65234170e-04,  -1.09504322e-04,
           6.04247529e-05,  -2.83776447e-06],
        [  2.46197208e-04,  -1.09504322e-04,   5.41010476e-04,
           1.22203572e-05,   1.06427576e-06],
        [ -4.58184091e-03,   6.04247529e-05,   1.22203572e-05,
           3.16582330e-03,  -5.07408790e-04],
        [  7.17341406e-04,  -2.83776447e-06,   1.06427576e-06,
          -5.07408790e-04,   8.33124928e-05]]))

In [21]:
har['ChaveII_new'] = np.exp(chave2014((har.E, har.Gravity, har.DBH_cm), -2.109, -0.896,  0.923,  2.794, -0.046))
har['ChaveII_new_error'] = (np.log(har.ChaveII_new) - np.log(har.AGB_kg))**2
cf = har.ChaveII_new_error.sum() / (har.shape[0]-5)
print "SEE:", cf ** 0.5
print "CF:", np.exp(cf / 2)
print "log CF:", cf / 2

SEE: 0.415318493142
CF: 1.0900730642
log CF: 0.0862447253731


## Maximum likelihood fit - Spicy

In [ ]:
from scipy.optimize import minimize

In [ ]:
def logLike(true, guess):
    n = len(true)
    error = true - guess
    sigma = np.std(error)
    f = -(n/2.0)*np.log(2*np.pi) - (n/2.0) * np.log(sigma**2) - \
            (1.0/(2*sigma**2) * np.dot(error.T,error))
    return f

def opt_chave2005(pars):
    y = pars[0] + pars[1] * np.log(har.DBH_cm) + pars[2] * np.log(har.DBH_cm)**2 + \
            pars[3] * np.log(har.DBH_cm)**3 + np.log(har.Gravity)
    log = logLike(np.log(har.AGB_kg), y)
    return -1 * log

def opt_chave2014(pars):
    y = pars[0] + pars[1] * har.E + pars[2] * np.log(har.Gravity) + pars[3] * np.log(har.DBH_cm) \
        + pars[4] * np.log(har.DBH_cm)**2 
    log = logLike(np.log(har.AGB_kg), y)
    return -1 * log

### Chave 2005

In [ ]:
#coeffs = np.array([-3.350, 3.688, -0.296, 0.026])
coeffs = np.array([-2.350, 2.688, -1.296, 0.026])
#opt_chave2005(coeffs)
res = minimize(opt_chave2005, coeffs, method='BFGS')

In [ ]:
res

### Chave 2014

In [ ]:
#coeffs = np.array([-2.109, -0.896,  0.923,  2.794, -0.046])
coeffs = np.array([-3.109, -1.896,  1.923,  1.794, 1.046])
res = minimize(opt_chave2014, coeffs, method='BFGS')

In [ ]:
res

## Maximum likelihood fit
### equation Chave I

In [ ]:
import pymc3

In [ ]:
mymodel = pymc3.Model()
with mymodel:
    #a + b * np.log(dap) + c * np.log(dap)**2 + d * np.log(dap)**3 + np.log(den)
    a = pymc3.Uniform('a')
    b = pymc3.Uniform('b')
    c = pymc3.Uniform('c')
    d = pymc3.Uniform('d')
    #sigma = pymc3.Normal('sigma', mu=0, sd=0.4)
    
    y_exp = a + b * np.log(har.DBH_cm) + c * np.log(har.DBH_cm)**2 + d * np.log(har.DBH_cm)**3 + \
        np.log(har.Gravity)
        
    Y_obs = pymc3.Normal('Y_obs', mu=y_exp, sd=0.4, observed=np.log(har.AGB_kg))
    
    trace = pymc3.sample(5000, njobs=2)

In [ ]:
pymc3.summary(trace)

In [ ]:
map_estimate = pymc3.find_MAP(model=mymodel)

In [ ]:
map_estimate
# 0.1606, 1, 0.262888, 0 