# Monte Carlo simulation

Steps to propagate biomass uncertainty through Monte Carlo simulation. Based on the proposal by Réjou-Méchain et al., 2017, Methods in Ecology and Evolution 8:1163-1167 and implemented in the R package *Biomass*.

Steps to propagate AGB uncertainty through Monte Carlo simulation.

1. Model tree diameter error. Could be normal distribution, parameters fitted from quality control measurements.  

2. Model wood density error. *Biomass* uses a truncated normal distribution based on the absolute ranges recorded at the wood density database (0.08-1.39 g/ml). A better way could be based on ancestral range reconstructed on a seed plant phylogeny.

3. Tree height error. *Biomass* takes a truncated normal distribution with the range(1.3-(maximum_height + 15)). However, this kind of error seems to by exponentially distributed, as it is more likely to record wrong values with taller trees. Parameters could be fitted with quality control measurements.

4. Allometric equation uncertainty. Depending on the allometric equation employed, coefficient distributions are estimated. *Biomass* estimates a posterior distribution for each equation using a MCMCMC.

5. Above ground biomass estimates are simulated for each tree n times using all the parameter distributions presented above, plus a random error. 


In [1]:
import pandas as pd
import numpy as np
import sqlalchemy as al
import db_utils
import comm
import pymc3
import matplotlib.pyplot as plt

Using matplotlib backend: Qt5Agg


In [25]:
# Load harvest data from Chave et al 2014
har = pd.read_csv("../Chave_harvest_db/Chave_GCB_Direct_Harvest_Data.csv")
loc = pd.read_csv("../Chave_harvest_db/Localities.csv")
loc['Forest_type'] = loc.Forest_type.str.replace(' forest','')
#print har.columns
#print loc.columns

In [26]:
def est_E(row):
    #E = ( 0.178 × TS-0.938 × CWD-6.61× PS ) ×10 −3
    ts = loc[loc.Abbreviation == row.Site]['Temp_Seasonality'].item()
    cwd = loc[loc.Abbreviation == row.Site]['CWD_mm_yr'].item()
    ps = loc[loc.Abbreviation == row.Site]['Precip_Seasonality_perc'].item()
    E = (0.178 * ts - 0.938 * cwd - 6.61 * ps) * 1e-3
    return E

har['E'] = har.apply(est_E, axis=1)

In [27]:
mymodel = pymc3.Model()
trace = None
with mymodel:
    #Priors
    a = pymc3.Normal('a', mu = -2.109, sd = 0.5)
    b = pymc3.Normal('b', mu = -0.896, sd = 0.5)
    c = pymc3.Normal('c', mu = 0.923, sd = 0.5)
    d = pymc3.Normal('d', mu = 2.794, sd = 0.5)
    e = pymc3.Normal('e', mu = -0.046, sd = 0.5)
    sigma = pymc3.HalfNormal('sigma', sd=1)
    
    # Allometric equation Chave 2014
    y_exp = a + b * har.E + c * np.log(har.Gravity) + d * np.log(har.DBH_cm) + e * np.log(har.DBH_cm)**2   
        
    # Likelihood function
    Y_obs = pymc3.Normal('Y_obs', mu=y_exp, sd=sigma, observed=np.log(har.AGB_kg))
    
    # Metropolis kernel
    #mstep = pymc3.Metropolis()
    #trace = pymc3.sample(50000, njobs=4, step=mstep)
    
    # NUTS kernel is default option for continuous parameters
    trace = pymc3.sample(5000, njobs=4)


Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
100%|██████████| 5500/5500 [10:15<00:00,  8.93it/s]
/home/nelson/anaconda2/lib/python2.7/site-packages/pymc3/step_methods/hmc/nuts.py:451: UserWarning: The acceptance probability in chain 3 does not match the target. It is 0.87994409202, but should be close to 0.8. Try to increase the number of tuning steps.
  % (self._chain_id, mean_accept, target_accept))


In [28]:
pymc3.diagnostics.effective_n(trace)

{'a': 5685.0,
 'b': 13199.0,
 'c': 11760.0,
 'd': 5637.0,
 'e': 5732.0,
 'sigma': 15036.0}

In [29]:
pymc3.summary(trace)


a:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------
  
  -2.109           0.081            0.001            [-2.269, -1.953]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|
  
  -2.266         -2.165         -2.109         -2.055         -1.950


b:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------------------------------------------
  
  -0.896           0.019            0.000            [-0.933, -0.858]

  Posterior quantiles:
  2.5            25             50             75             97.5
  |--------------|==============|==============|--------------|
  
  -0.933         -0.909         -0.896         -0.883         -0.858


c:

  Mean             SD               MC Error         95% HPD interval
  -------------------------------

In [30]:
pymc3.traceplot(trace)

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fa18a816210>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x7fa198a554d0>]], dtype=object)

array([-2.10862669, -2.08049102, -2.24401702, -2.10929088, -2.18200722,
       -2.1394579 , -2.13474154, -2.07843708, -1.98463348, -2.06295352,
       -2.06875845, -2.13846038, -2.18488653, -2.07146634, -2.10828979,
       -2.16151448, -2.1224068 , -1.99180246, -2.18585067, -2.12354344,
       -2.14988525, -2.26795443, -2.06662012, -2.10525392, -2.06896965,
       -1.9963097 , -2.14173161, -2.12786656, -2.07558603, -2.10136545,
       -2.10383957, -2.13608586, -2.13289714, -2.07557746, -2.14741872,
       -2.14581706, -2.06052572, -2.09066897, -2.17410247, -2.17285447,
       -2.03479301, -2.11313254, -2.13347814, -2.00916358, -2.15453316,
       -2.15334146, -1.97884577, -2.14238751, -2.1143575 , -2.10929088,
       -2.20482798, -2.19148432, -2.04620288, -2.24468697, -2.09540485,
       -2.09493605, -1.88025121, -1.98559321, -2.18127137, -1.98771535,
       -2.03136565, -2.25510265, -2.10745567, -1.95127274, -2.19207252,
       -2.14691305, -2.13153486, -2.0834796 , -2.06598653, -2.15

In [12]:
# Import plot data

user = ''
password = ''
database = ''

engine = al.create_engine(
    'mysql+mysqldb://{0}:{1}@localhost/{2}?charset=utf8&use_unicode=1&unix_socket=/var/run/mysqld/mysqld.sock'.format(
    user, password, database))

conn = engine.connect()


In [13]:
accnames = db_utils.acctax(conn)

In [14]:
table = db_utils.dasotab('Quimera', conn, 1, accepted_taxa = accnames)

In [16]:
table.columns

Index([u'Diameter', u'Height', u'Family', u'Genus', u'Epithet'], dtype='object')

In [18]:
densities_file = '/home/nelson/Documents/IDEAM/GlobalWoodDensityDB/gwddb_20180113.csv'
elevation_raster = '/home/nelson/Documents/IDEAM/cust_layers/alt.tif'
precipitation_raster = '/home/nelson/Documents/IDEAM/cust_layers/precp.tif'
chave_E_raster = '/home/nelson/Documents/IDEAM/Chave_E/E.bil'

myplot = comm.Plot(dataframe=table)
myplot.name = 1
myplot.purify()
myplot.coordinates = db_utils.coords('Quimera', conn, 1)
myplot.set_holdridge(elevation_raster, precipitation_raster)
myplot.set_chave_forest(precipitation_raster)
myplot.set_E(chave_E_raster)
myplot.densities_from_file(densities_file)

In [21]:
myplot.taxa.columns

Index([u'Family', u'Genus', u'Epithet', u'TaxonID', u'Density'], dtype='object')

In [42]:
# Sample tree diameter and wood density uncertainty values

iters = 100

# Sample posterior distribution of parameters
myas = np.random.choice(trace.get_values('a', burn = 1000, combine=True), 100)
mybs = np.random.choice(trace.get_values('b', burn = 1000, combine=True), 100)
mycs = np.random.choice(trace.get_values('c', burn = 1000, combine=True), 100)
myds = np.random.choice(trace.get_values('d', burn = 1000, combine=True), 100)
myes = np.random.choice(trace.get_values('e', burn = 1000, combine=True), 100)

AGB = []

for tree in myplot.stems.itertuples():
    AGB.append([])
    sdd = tree.Diameter / 100.0
    diams = np.random.normal(tree.Diameter, sdd, iters)

    wd = myplot.taxa[myplot.taxa.TaxonID == tree.TaxonID]['Density'].item()
    sdwd = 0.01
    wds = np.random.normal(wd, sdwd, iters)

    for sdi, swd, sa, sb, sc, sd, se in zip(diams, wds, myas, mybs, mycs, myds, myes):
        agb = sa + sb * myplot.E + sc * np.log(swd) + sd * np.log(sdi) + se * np.log(sdi)**2
        AGB[-1].append(agb)
        
AGB = np.array(AGB)

In [51]:
total_agb = []
for x in xrange(5000):
    this_agb = 0.0
    for t in xrange(AGB.shape[0]):
        this_agb += np.random.choice(AGB[t], 1)
    total_agb.append(this_agb[0])


In [55]:
plt.hist(total_agb, bins=100)

(array([   1.,    0.,    0.,    0.,    0.,    0.,    0.,    1.,    1.,
           0.,    1.,    1.,    1.,    3.,    1.,    6.,    4.,    3.,
           5.,    7.,    7.,    9.,   15.,   12.,   20.,   14.,   24.,
          32.,   32.,   52.,   44.,   47.,   55.,   62.,   71.,   60.,
          86.,   95.,  114.,  107.,  119.,  123.,  115.,  140.,  147.,
         163.,  148.,  153.,  175.,  140.,  156.,  174.,  138.,  160.,
         141.,  138.,  145.,  144.,  129.,  123.,  101.,   91.,  118.,
          92.,   80.,   77.,   83.,   74.,   49.,   36.,   37.,   45.,
          28.,   42.,   28.,   36.,   24.,   17.,   12.,   15.,    8.,
           6.,    8.,    3.,    4.,    4.,    4.,    4.,    2.,    4.,
           1.,    0.,    1.,    0.,    1.,    0.,    0.,    0.,    0.,    1.]),
 array([ 362.04574784,  362.1785108 ,  362.31127375,  362.4440367 ,
         362.57679965,  362.7095626 ,  362.84232555,  362.97508851,
         363.10785146,  363.24061441,  363.37337736,  363.50614031,
      